--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/MCBE-trustonline/EconomySystem
build-by-default: true
branches:
- main
projects:
  EconomySystem:
    path: ""
    lint:
      phpstan: false
    libs:
      - src: sky-min/CommandLib/CommandLib
        version: ^1.4.0
      - src: sky-min/InventoryLib/InventoryLib
        version: ^2.4.7
      - src: https://poggit.pmmp.io/ci/sky-min/DataConfig
        version: ^1.0.1
...
