--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/MCBE-trustonline/EconomySystem
build-by-default: true
branches:
- main
projects:
  EconomySystem:
    path: ""
    libs:
      - src: sky-min/CommandLib/CommandLib
        version: ^1.4.0
      - src: sky-min/InventoryLib/InventoryLib
        version: ^2.4.7
      - src: sky-min/Data/Data
        version: ^1.0.0
      - src: sky-min/SkinLib/SkinLib
        version: ^3.0.1
...
