--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/MCBE-trustonline/EconomySystem
build-by-default: true
branches:
- main
projects:
  EconomySystem:
    path: ""
    libs:
      - src: sky-min/CommandLib/CommandLib
        version: ^1.4.0
      - src: sky-min/DataConfig/Data
        version: ^2.0.7
      - src: sky-min/AsyncQueue/AsyncQueue
        version: ^1.0.1
...
